# Generated by Django 5.2 on 2025-06-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_doctor_user_alter_user_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
