# Generated by Django 5.2 on 2025-06-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
