# Generated by Django 5.2 on 2025-06-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('terminé', 'Terminé'), ('confirmé', 'Confirmé')], default='pending', max_length=20),
        ),
    ]
